/* *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁*.

Licensed under the  GPL-3.0 License;
you may not use this file except in compliance with the License.

Whats bot - ιnѕane bot
*/

const Shazz = require('../events');
const {MessageType, MessageOptions, Mimetype} = require('@adiwajshing/baileys');
const axios = require('axios');
const Config = require('../config');
const {spawnSync} = require('child_process');
const fs = require('fs');

const NNVL = "logo to image all manu.. *𝚄𝚜𝚎 𝚝𝚑𝚎 𝚏𝚘𝚕𝚕𝚘𝚠𝚒𝚗𝚐 𝚌𝚘𝚖𝚖𝚊𝚗𝚍𝚜 𝚝𝚘 𝚐𝚎𝚝 𝚝𝚑𝚎 𝚆𝚘𝚛𝚍 𝙿𝚒𝚌𝚝𝚞𝚛𝚎 𝙲𝚘𝚗𝚟𝚎𝚛𝚝𝚎𝚛 𝚖𝚎𝚗𝚞*"

if (Config.WORKTYPE == 'private') {
     
        Shazz.addCommand({pattern: 'logomaker', fromMe: true, desc: NNVL}, (async (message, match) => {
      await message.sendMessage('👑 **˩σɢσ мακɛя** 👑\n  \n*𝚄𝚜𝚎 𝚝𝚑𝚎 𝚏𝚘𝚕𝚕𝚘𝚠𝚒𝚗𝚐 𝚌𝚘𝚖𝚖𝚊𝚗𝚍𝚜 𝚝𝚘 𝚐𝚎𝚝 𝚝𝚑𝚎 𝚆𝚘𝚛𝚍 𝙿𝚒𝚌𝚝𝚞𝚛𝚎 𝙲𝚘𝚗𝚟𝚎𝚛𝚝𝚎𝚛 𝚖𝚎𝚗𝚞*\n\n\n\n💠 .logo1\n\n💠 .logo2\n\n💠 .logo3\n\n💠 .logo4\n\n💠 .logo5\n\n💠 .logo6\n\n💠 .logo7\n\n💠 .logo8\n\n\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo1', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.dota2*\n✨Desc: it makes metal dota2 logo\n💍 Example : *.dota2 ιnѕane*\n\n❄️Usage: *.avo*\n✨Desc: it makes metal avo logo\n💍 Example : *.avo ιnѕane*\n\n❄️Usage: *.1lol*\n✨Desc: it makes metal 1lol logo\n💍 Example : *.1lol ιnѕane*\n\n❄️Usage: *.2lol*\n✨Desc: it makes metal 2lol logo\n💍 Example : *.2lol ιnѕane*\n\n❄️Usage: *.3lol*\n✨Desc: it makes metal 3lol logo\n💍 Example : *.3lol Ravind*\n\n❄️Usage: *.stars*\n✨Desc: it makes metal stars logo\n💍 Example : *.stara ιnѕane*\n\n❄️Usage: *.fur*\n✨Desc: it makes metal fur logo\n💍 Example : *.fur ιnѕane*\n\n❄️Usage: *.gerbang*\n✨Desc: it makes metal gerbang logo\n💍 Example : *.gerbang ιnѕane*\n\n❄️Usage: *.grad*\n✨Desc: it makes metal grad logo\n💍 Example : *.grad ιnѕane*\n\n❄️Usage: *.1spark*\n✨Desc: it makes metal 1spark logo\n💍 Example : *.1spark ιnѕane*\n\n❄️Usage: *.2spark*\n✨Desc: it makes metal 2spark logo\n💍 Example : *.2spark ιnѕane*\n\n❄️Usage: *.3spark*\n✨Desc: it makes metal 3spark logo\n💍 Example : *.3spark ιnѕane*\n\n❄️Usage: *.4spark*\n✨Desc: it makes metal 4spark logo\n💍 Example : *.4spark ιnѕane*\n\n❄️Usage: *.5spark*\n✨Desc: it makes metal 5spark logo\n💍 Example : *.5spark ιnѕane*\n\n❄️Usage: *.biscuit*\n✨Desc: it makes metal biscuit logo\n💍 Example : *.biscuit ιnѕane*\n\n❄️Usage: *.fish*\n✨Desc: it makes metal fisha logo\n💍 Example : *.fish ιnѕane*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow ιnѕane*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny ιnѕane*\n\n❄️Usage: *.fruit*\n✨Desc: it makes metal fruit logo\n💍 Example : *.fruit ιnѕane*\n\n❄️Usage: *.bluemetal*\n✨Desc: it makes metal bluemetal logo\n💍 Example : *.bluemetal ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Shazz.addCommand({pattern: 'logo2', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.1candi*\n✨Desc: it makes metal 1candi logo\n💍 Example : *.1candi ιnѕane*\n\n❄️Usage: *.2carbon*\n✨Desc: it makes metal 2carbon logo\n💍 Example : *.2carbon ιnѕane*\n\n❄️Usage: *.2metal*\n✨Desc: it makes metal 2metal logo\n💍 Example : *.2metal ιnѕane*\n\n❄️Usage: *.1glitter*\n✨Desc: it makes metal 1glitter logo\n💍 Example : *.1glitter ιnѕane*\n\n❄️Usage: *.2glitter*\n✨Desc: it makes metal 2glitter logo\n💍 Example : *.2glitter Ravind*\n\n❄️Usage: *.3glitter*\n✨Desc: it makes metal 3glitter logo\n💍 Example : *.3glitter ιnѕane*\n\n❄️Usage: *.4glitter*\n✨Desc: it makes metal 4glitter logo\n💍 Example : *.4glitter ιnѕane*\n\n❄️Usage: *.5glitter*\n✨Desc: it makes metal 5glitter logo\n💍 Example : *.5glitter ιnѕane*\n\n❄️Usage: *.6glitter*\n✨Desc: it makes metal 6glitter logo\n💍 Example : *.6glitter ιnѕane*\n\n❄️Usage: *.7glitter*\n✨Desc: it makes metal 7glitter logo\n💍 Example : *.7glitter ιnѕane*\n\n❄️Usage: *.1jewelry*\n✨Desc: it makes metal 1jewelry logo\n💍 Example : *.1jewelry ιnѕane*\n\n❄️Usage: *.2jewelry*\n✨Desc: it makes metal 2jewelry logo\n💍 Example : *.2jewelry ιnѕane*\n\n❄️Usage: *.3jewelry*\n✨Desc: it makes metal 3jewelry logo\n💍 Example : *.3jewelry ιnѕane*\n\n❄️Usage: *.4jewelry*\n✨Desc: it makes metal 4jewelry logo\n💍 Example : *.4jewelry ιnѕane*\n\n❄️Usage: *.5jewelry*\n✨Desc: it makes metal 5jewelry logo\n💍 Example : *.5jewelry ιnѕane*\n\n❄️Usage: *.6jewelry*\n✨Desc: it makes metal 6jewelry logo\n💍 Example : *.6jewelry ιnѕane*\n\n❄️Usage: *.7jewelry*\n✨Desc: it makes metal 7jewelry logo\n💍 Example : *.7jewelry ιnѕane*\n\n❄️Usage: *.8jewelry*\n✨Desc: it makes metal 8jewelry logo\n💍 Example : *.8jewelry ιnѕane*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny ιnѕane*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Shazz.addCommand({pattern: 'logo3', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.3cake*\n✨Desc: it makes metal 3cake logo\n💍 Example : *.3cake ιnѕane*\n\n❄️Usage: *.captain*\n✨Desc: it makes metal captain logo\n💍 Example : *.captain ιnѕane*\n\n❄️Usage: *.bagel*\n✨Desc: it makes metal bagel logo\n💍 Example : *.bagel ιnѕane*\n\n❄️Usage: *.1gem*\n✨Desc: it makes metal 1gem logo\n💍 Example : *.1gem ιnѕane*\n\n❄️Usage: *.berry*\n✨Desc: it makes metal berry logo\n💍 Example : *.berry ιnѕane*\n\n❄️Usage: *.2blood*\n✨Desc: it makes metal 2blood logo\n💍 Example : *.2blood ιnѕane*\n\n❄️Usage: *.3blood*\n✨Desc: it makes metal 3blood logo\n💍 Example : *.3blood ιnѕane*\n\n❄️Usage: *.1glass*\n✨Desc: it makes metal 1glass logo\n💍 Example : *.1glass ιnѕane*\n\n❄️Usage: *.lava*\n✨Desc: it makes metal lava logo\n💍 Example : *.lava ιnѕane*\n\n❄️Usage: *.rock*\n✨Desc: it makes metal rock logo\n💍 Example : *.rock ιnѕane*\n\n❄️Usage: *.1decora*\n✨Desc: it makes metal 1decora logo\n💍 Example : *.1decora ιnѕane*\n\n❄️Usage: *.2decora*\n✨Desc: it makes metal 2decora logo\n💍 Example : *.2decora ιnѕane*\n\n❄️Usage: *.3decora*\n✨Desc: it makes metal 3decora logo\n💍 Example : *.3decora ιnѕane*\n\n❄️Usage: *.1foil*\n✨Desc: it makes metal 1foil logo\n💍 Example : *.1foil ιnѕane*\n\n❄️Usage: *.2foil*\n✨Desc: it makes metal 2foil logo\n💍 Example : *.2foil ιnѕane*\n\n❄️Usage: *.3foil*\n✨Desc: it makes metal 3foil logo\n💍 Example : *.3foil ιnѕane*\n\n❄️Usage: *.4foil*\n✨Desc: it makes metal 4foil logo\n💍 Example : *.4foil ιnѕane*\n\n❄️Usage: *.5foil*\n✨Desc: it makes metal 5foil logo\n💍 Example : *.5foil ιnѕane*\n\n❄️Usage: *.6foil*\n✨Desc: it makes metal 6foil logo\n💍 Example : *.6foil ιnѕane*\n\n❄️Usage: *.7foil*\n✨Desc: it makes metal 7foil logo\n💍 Example : *.7foil ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo4', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.steel*\n✨Desc: it makes metal steel logo\n💍 Example : *.steel ιnѕane*\n\n❄️Usage: *.1glossy*\n✨Desc: it makes metal 1glossy logo\n💍 Example : *.1glossy ιnѕane*\n\n❄️Usage: *.2glossy*\n✨Desc: it makes metal 2glossy logo\n💍 Example : *.2glossy ιnѕane*\n\n❄️Usage: *.denim*\n✨Desc: it makes metal denim logo\n💍 Example : *.denim ιnѕane*\n\n❄️Usage: *.joker*\n✨Desc: it makes metal joker logo\n💍 Example : *.joker ιnѕane*\n\n❄️Usage: *.wicker*\n✨Desc: it makes metal wicker logo\n💍 Example : *.wicker ιnѕane*\n\n❄️Usage: *.skeleton*\n✨Desc: it makes metal skeleton logo\n💍 Example : *.skeleton ιnѕane*\n\n❄️Usage: *.xmas3d*\n✨Desc: it makes metal xmas3d logo\n💍 Example : *.xmas3d ιnѕane*\n\n❄️Usage: *.helloween*\n✨Desc: it makes metal helloween logo\n💍 Example : *.helloween ιnѕane*\n\n❄️Usage: *.neon1s*\n✨Desc: it makes metal neon1s logo\n💍 Example : *.neon1s ιnѕane*\n\n❄️Usage: *.new1y*\n✨Desc: it makes metal new1y logo\n💍 Example : *.new1y ιnѕane*\n\n❄️Usage: *.1fabric*\n✨Desc: it makes metal 1fabric logo\n💍 Example : *.1fabric ιnѕane*\n\n❄️Usage: *.purpule*\n✨Desc: it makes metal purpule logo\n💍 Example : *.purpule ιnѕane*\n\n❄️Usage: *.holo3d*\n✨Desc: it makes metal holo3d logo\n💍 Example : *.holo3d ιnѕane*\n\n❄️Usage: *.minion3d*\n✨Desc: it makes metal minion3d logo\n💍 Example : *.minion3d ιnѕane*\n\n❄️Usage: *.neongalaxy*\n✨Desc: it makes metal neongalaxy logo\n💍 Example : *.neongalaxy ιnѕane*\n\n❄️Usage: *.darkgold*\n✨Desc: it makes metal darkgold logo\n💍 Example : *.darkgold ιnѕane*\n\n❄️Usage: *.1sandwriting*\n✨Desc: it makes metal 1sandwriting logo\n💍 Example : *.1sandwriting ιnѕane*\n\n❄️Usage: *.cloudsky*\n✨Desc: it makes metal cloudsky logo\n💍 Example : *.cloudsky ιnѕane*\n\n❄️Usage: *.3dluxury*\n✨Desc: it makes metal 3dluxury logo\n💍 Example : *.3dluxury ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.sandsum*\n✨Desc: it makes metal sandsum logo\n💍 Example : *.sandsum ιnѕane*\n\n❄️Usage: *.1917*\n✨Desc: it makes metal 1917 logo\n💍 Example : *.1917 ιnѕane*\n\n❄️Usage: *.vlogo*\n✨Desc: it makes metal vlogo logo\n💍 Example : *.vlogo ιnѕane*\n\n❄️Usage: *.plogo*\n✨Desc: it makes metal plogo logo\n💍 Example : *.plogo ιnѕane*\n\n❄️Usage: *.colorlogo*\n✨Desc: it makes metal colorlogo logo\n💍 Example : *.colorlogo ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
}

else if (Config.WORKTYPE == 'public') {

     Shazz.addCommand({pattern: 'sewmaker', fromMe: true, desc: NNVL}, (async (message, match) => {
      await message.sendMessage('👑 **˩σɢσ мακɛя** 👑\n  \n*𝚄𝚜𝚎 𝚝𝚑𝚎 𝚏𝚘𝚕𝚕𝚘𝚠𝚒𝚗𝚐 𝚌𝚘𝚖𝚖𝚊𝚗𝚍𝚜 𝚝𝚘 𝚐𝚎𝚝 𝚝𝚑𝚎 𝚆𝚘𝚛𝚍 𝙿𝚒𝚌𝚝𝚞𝚛𝚎 𝙲𝚘𝚗𝚟𝚎𝚛𝚝𝚎𝚛 𝚖𝚎𝚗𝚞*\n\n\n\n💠 .logo1\n\n💠 .logo2\n\n💠 .logo3\n\n💠 .logo4\n\n💠 .logo5\n\n💠 .logo6\n\n💠 .logo7\n\n💠 .logo8\n\n\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo1', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.dota2*\n✨Desc: it makes metal dota2 logo\n💍 Example : *.dota2 ιnѕane*\n\n❄️Usage: *.avo*\n✨Desc: it makes metal avo logo\n💍 Example : *.avo ιnѕane*\n\n❄️Usage: *.1lol*\n✨Desc: it makes metal 1lol logo\n💍 Example : *.1lol ιnѕane*\n\n❄️Usage: *.2lol*\n✨Desc: it makes metal 2lol logo\n💍 Example : *.2lol ιnѕane*\n\n❄️Usage: *.3lol*\n✨Desc: it makes metal 3lol logo\n💍 Example : *.3lol Ravind*\n\n❄️Usage: *.stars*\n✨Desc: it makes metal stars logo\n💍 Example : *.stara ιnѕane*\n\n❄️Usage: *.fur*\n✨Desc: it makes metal fur logo\n💍 Example : *.fur ιnѕane*\n\n❄️Usage: *.gerbang*\n✨Desc: it makes metal gerbang logo\n💍 Example : *.gerbang ιnѕane*\n\n❄️Usage: *.grad*\n✨Desc: it makes metal grad logo\n💍 Example : *.grad ιnѕane*\n\n❄️Usage: *.1spark*\n✨Desc: it makes metal 1spark logo\n💍 Example : *.1spark ιnѕane*\n\n❄️Usage: *.2spark*\n✨Desc: it makes metal 2spark logo\n💍 Example : *.2spark ιnѕane*\n\n❄️Usage: *.3spark*\n✨Desc: it makes metal 3spark logo\n💍 Example : *.3spark ιnѕane*\n\n❄️Usage: *.4spark*\n✨Desc: it makes metal 4spark logo\n💍 Example : *.4spark ιnѕane*\n\n❄️Usage: *.5spark*\n✨Desc: it makes metal 5spark logo\n💍 Example : *.5spark ιnѕane*\n\n❄️Usage: *.biscuit*\n✨Desc: it makes metal biscuit logo\n💍 Example : *.biscuit ιnѕane*\n\n❄️Usage: *.fish*\n✨Desc: it makes metal fisha logo\n💍 Example : *.fish ιnѕane*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow ιnѕane*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny ιnѕane*\n\n❄️Usage: *.fruit*\n✨Desc: it makes metal fruit logo\n💍 Example : *.fruit ιnѕane*\n\n❄️Usage: *.bluemetal*\n✨Desc: it makes metal bluemetal logo\n💍 Example : *.bluemetal ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Shazz.addCommand({pattern: 'logo2', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.1candi*\n✨Desc: it makes metal 1candi logo\n💍 Example : *.1candi ιnѕane*\n\n❄️Usage: *.2carbon*\n✨Desc: it makes metal 2carbon logo\n💍 Example : *.2carbon ιnѕane*\n\n❄️Usage: *.2metal*\n✨Desc: it makes metal 2metal logo\n💍 Example : *.2metal ιnѕane*\n\n❄️Usage: *.1glitter*\n✨Desc: it makes metal 1glitter logo\n💍 Example : *.1glitter ιnѕane*\n\n❄️Usage: *.2glitter*\n✨Desc: it makes metal 2glitter logo\n💍 Example : *.2glitter Ravind*\n\n❄️Usage: *.3glitter*\n✨Desc: it makes metal 3glitter logo\n💍 Example : *.3glitter ιnѕane*\n\n❄️Usage: *.4glitter*\n✨Desc: it makes metal 4glitter logo\n💍 Example : *.4glitter ιnѕane*\n\n❄️Usage: *.5glitter*\n✨Desc: it makes metal 5glitter logo\n💍 Example : *.5glitter ιnѕane*\n\n❄️Usage: *.6glitter*\n✨Desc: it makes metal 6glitter logo\n💍 Example : *.6glitter ιnѕane*\n\n❄️Usage: *.7glitter*\n✨Desc: it makes metal 7glitter logo\n💍 Example : *.7glitter ιnѕane*\n\n❄️Usage: *.1jewelry*\n✨Desc: it makes metal 1jewelry logo\n💍 Example : *.1jewelry ιnѕane*\n\n❄️Usage: *.2jewelry*\n✨Desc: it makes metal 2jewelry logo\n💍 Example : *.2jewelry ιnѕane*\n\n❄️Usage: *.3jewelry*\n✨Desc: it makes metal 3jewelry logo\n💍 Example : *.3jewelry ιnѕane*\n\n❄️Usage: *.4jewelry*\n✨Desc: it makes metal 4jewelry logo\n💍 Example : *.4jewelry ιnѕane*\n\n❄️Usage: *.5jewelry*\n✨Desc: it makes metal 5jewelry logo\n💍 Example : *.5jewelry ιnѕane*\n\n❄️Usage: *.6jewelry*\n✨Desc: it makes metal 6jewelry logo\n💍 Example : *.6jewelry ιnѕane*\n\n❄️Usage: *.7jewelry*\n✨Desc: it makes metal 7jewelry logo\n💍 Example : *.7jewelry ιnѕane*\n\n❄️Usage: *.8jewelry*\n✨Desc: it makes metal 8jewelry logo\n💍 Example : *.8jewelry ιnѕane*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny ιnѕane*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Shazz.addCommand({pattern: 'logo3', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.3cake*\n✨Desc: it makes metal 3cake logo\n💍 Example : *.3cake ιnѕane*\n\n❄️Usage: *.captain*\n✨Desc: it makes metal captain logo\n💍 Example : *.captain ιnѕane*\n\n❄️Usage: *.bagel*\n✨Desc: it makes metal bagel logo\n💍 Example : *.bagel ιnѕane*\n\n❄️Usage: *.1gem*\n✨Desc: it makes metal 1gem logo\n💍 Example : *.1gem ιnѕane*\n\n❄️Usage: *.berry*\n✨Desc: it makes metal berry logo\n💍 Example : *.berry ιnѕane*\n\n❄️Usage: *.2blood*\n✨Desc: it makes metal 2blood logo\n💍 Example : *.2blood ιnѕane*\n\n❄️Usage: *.3blood*\n✨Desc: it makes metal 3blood logo\n💍 Example : *.3blood ιnѕane*\n\n❄️Usage: *.1glass*\n✨Desc: it makes metal 1glass logo\n💍 Example : *.1glass ιnѕane*\n\n❄️Usage: *.lava*\n✨Desc: it makes metal lava logo\n💍 Example : *.lava ιnѕane*\n\n❄️Usage: *.rock*\n✨Desc: it makes metal rock logo\n💍 Example : *.rock ιnѕane*\n\n❄️Usage: *.1decora*\n✨Desc: it makes metal 1decora logo\n💍 Example : *.1decora ιnѕane*\n\n❄️Usage: *.2decora*\n✨Desc: it makes metal 2decora logo\n💍 Example : *.2decora ιnѕane*\n\n❄️Usage: *.3decora*\n✨Desc: it makes metal 3decora logo\n💍 Example : *.3decora ιnѕane*\n\n❄️Usage: *.1foil*\n✨Desc: it makes metal 1foil logo\n💍 Example : *.1foil ιnѕane*\n\n❄️Usage: *.2foil*\n✨Desc: it makes metal 2foil logo\n💍 Example : *.2foil ιnѕane*\n\n❄️Usage: *.3foil*\n✨Desc: it makes metal 3foil logo\n💍 Example : *.3foil ιnѕane*\n\n❄️Usage: *.4foil*\n✨Desc: it makes metal 4foil logo\n💍 Example : *.4foil ιnѕane*\n\n❄️Usage: *.5foil*\n✨Desc: it makes metal 5foil logo\n💍 Example : *.5foil ιnѕane*\n\n❄️Usage: *.6foil*\n✨Desc: it makes metal 6foil logo\n💍 Example : *.6foil ιnѕane*\n\n❄️Usage: *.7foil*\n✨Desc: it makes metal 7foil logo\n💍 Example : *.7foil ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo4', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.steel*\n✨Desc: it makes metal steel logo\n💍 Example : *.steel ιnѕane*\n\n❄️Usage: *.1glossy*\n✨Desc: it makes metal 1glossy logo\n💍 Example : *.1glossy ιnѕane*\n\n❄️Usage: *.2glossy*\n✨Desc: it makes metal 2glossy logo\n💍 Example : *.2glossy ιnѕane*\n\n❄️Usage: *.denim*\n✨Desc: it makes metal denim logo\n💍 Example : *.denim ιnѕane*\n\n❄️Usage: *.joker*\n✨Desc: it makes metal joker logo\n💍 Example : *.joker ιnѕane*\n\n❄️Usage: *.wicker*\n✨Desc: it makes metal wicker logo\n💍 Example : *.wicker ιnѕane*\n\n❄️Usage: *.skeleton*\n✨Desc: it makes metal skeleton logo\n💍 Example : *.skeleton ιnѕane*\n\n❄️Usage: *.xmas3d*\n✨Desc: it makes metal xmas3d logo\n💍 Example : *.xmas3d ιnѕane*\n\n❄️Usage: *.helloween*\n✨Desc: it makes metal helloween logo\n💍 Example : *.helloween ιnѕane*\n\n❄️Usage: *.neon1s*\n✨Desc: it makes metal neon1s logo\n💍 Example : *.neon1s ιnѕane*\n\n❄️Usage: *.new1y*\n✨Desc: it makes metal new1y logo\n💍 Example : *.new1y ιnѕane*\n\n❄️Usage: *.1fabric*\n✨Desc: it makes metal 1fabric logo\n💍 Example : *.1fabric ιnѕane*\n\n❄️Usage: *.purpule*\n✨Desc: it makes metal purpule logo\n💍 Example : *.purpule ιnѕane*\n\n❄️Usage: *.holo3d*\n✨Desc: it makes metal holo3d logo\n💍 Example : *.holo3d ιnѕane*\n\n❄️Usage: *.minion3d*\n✨Desc: it makes metal minion3d logo\n💍 Example : *.minion3d ιnѕane*\n\n❄️Usage: *.neongalaxy*\n✨Desc: it makes metal neongalaxy logo\n💍 Example : *.neongalaxy ιnѕane*\n\n❄️Usage: *.darkgold*\n✨Desc: it makes metal darkgold logo\n💍 Example : *.darkgold ιnѕane*\n\n❄️Usage: *.1sandwriting*\n✨Desc: it makes metal 1sandwriting logo\n💍 Example : *.1sandwriting ιnѕane*\n\n❄️Usage: *.cloudsky*\n✨Desc: it makes metal cloudsky logo\n💍 Example : *.cloudsky ιnѕane*\n\n❄️Usage: *.3dluxury*\n✨Desc: it makes metal 3dluxury logo\n💍 Example : *.3dluxury ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo', fromMe: true, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.sandsum*\n✨Desc: it makes metal sandsum logo\n💍 Example : *.sandsum ιnѕane*\n\n❄️Usage: *.1917*\n✨Desc: it makes metal 1917 logo\n💍 Example : *.1917 ιnѕane*\n\n❄️Usage: *.vlogo*\n✨Desc: it makes metal vlogo logo\n💍 Example : *.vlogo ιnѕane*\n\n❄️Usage: *.plogo*\n✨Desc: it makes metal plogo logo\n💍 Example : *.plogo ιnѕane*\n\n❄️Usage: *.colorlogo*\n✨Desc: it makes metal colorlogo logo\n💍 Example : *.colorlogo ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'sewmaker', fromMe: false, desc: NNVL}, (async (message, match) => {
      await message.sendMessage('👑 **˩σɢσ мακɛя** 👑\n  \n*𝚄𝚜𝚎 𝚝𝚑𝚎 𝚏𝚘𝚕𝚕𝚘𝚠𝚒𝚗𝚐 𝚌𝚘𝚖𝚖𝚊𝚗𝚍𝚜 𝚝𝚘 𝚐𝚎𝚝 𝚝𝚑𝚎 𝚆𝚘𝚛𝚍 𝙿𝚒𝚌𝚝𝚞𝚛𝚎 𝙲𝚘𝚗𝚟𝚎𝚛𝚝𝚎𝚛 𝚖𝚎𝚗𝚞*\n\n\n\n💠 .logo1\n\n💠 .logo2\n\n💠 .logo3\n\n💠 .logo4\n\n💠 .logo5\n\n💠 .logo6\n\n💠 .logo7\n\n💠 .logo8\n\n\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo1', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.dota2*\n✨Desc: it makes metal dota2 logo\n💍 Example : *.dota2 ιnѕane*\n\n❄️Usage: *.avo*\n✨Desc: it makes metal avo logo\n💍 Example : *.avo ιnѕane*\n\n❄️Usage: *.1lol*\n✨Desc: it makes metal 1lol logo\n💍 Example : *.1lol ιnѕane*\n\n❄️Usage: *.2lol*\n✨Desc: it makes metal 2lol logo\n💍 Example : *.2lol ιnѕane*\n\n❄️Usage: *.3lol*\n✨Desc: it makes metal 3lol logo\n💍 Example : *.3lol Ravind*\n\n❄️Usage: *.stars*\n✨Desc: it makes metal stars logo\n💍 Example : *.stara ιnѕane*\n\n❄️Usage: *.fur*\n✨Desc: it makes metal fur logo\n💍 Example : *.fur ιnѕane*\n\n❄️Usage: *.gerbang*\n✨Desc: it makes metal gerbang logo\n💍 Example : *.gerbang ιnѕane*\n\n❄️Usage: *.grad*\n✨Desc: it makes metal grad logo\n💍 Example : *.grad ιnѕane*\n\n❄️Usage: *.1spark*\n✨Desc: it makes metal 1spark logo\n💍 Example : *.1spark ιnѕane*\n\n❄️Usage: *.2spark*\n✨Desc: it makes metal 2spark logo\n💍 Example : *.2spark ιnѕane*\n\n❄️Usage: *.3spark*\n✨Desc: it makes metal 3spark logo\n💍 Example : *.3spark ιnѕane*\n\n❄️Usage: *.4spark*\n✨Desc: it makes metal 4spark logo\n💍 Example : *.4spark ιnѕane*\n\n❄️Usage: *.5spark*\n✨Desc: it makes metal 5spark logo\n💍 Example : *.5spark ιnѕane*\n\n❄️Usage: *.biscuit*\n✨Desc: it makes metal biscuit logo\n💍 Example : *.biscuit ιnѕane*\n\n❄️Usage: *.fish*\n✨Desc: it makes metal fisha logo\n💍 Example : *.fish ιnѕane*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow ιnѕane*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny ιnѕane*\n\n❄️Usage: *.fruit*\n✨Desc: it makes metal fruit logo\n💍 Example : *.fruit ιnѕane*\n\n❄️Usage: *.bluemetal*\n✨Desc: it makes metal bluemetal logo\n💍 Example : *.bluemetal ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Shazz.addCommand({pattern: 'logo2', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.1candi*\n✨Desc: it makes metal 1candi logo\n💍 Example : *.1candi ιnѕane*\n\n❄️Usage: *.2carbon*\n✨Desc: it makes metal 2carbon logo\n💍 Example : *.2carbon ιnѕane*\n\n❄️Usage: *.2metal*\n✨Desc: it makes metal 2metal logo\n💍 Example : *.2metal ιnѕane*\n\n❄️Usage: *.1glitter*\n✨Desc: it makes metal 1glitter logo\n💍 Example : *.1glitter ιnѕane*\n\n❄️Usage: *.2glitter*\n✨Desc: it makes metal 2glitter logo\n💍 Example : *.2glitter Ravind*\n\n❄️Usage: *.3glitter*\n✨Desc: it makes metal 3glitter logo\n💍 Example : *.3glitter ιnѕane*\n\n❄️Usage: *.4glitter*\n✨Desc: it makes metal 4glitter logo\n💍 Example : *.4glitter ιnѕane*\n\n❄️Usage: *.5glitter*\n✨Desc: it makes metal 5glitter logo\n💍 Example : *.5glitter ιnѕane*\n\n❄️Usage: *.6glitter*\n✨Desc: it makes metal 6glitter logo\n💍 Example : *.6glitter ιnѕane*\n\n❄️Usage: *.7glitter*\n✨Desc: it makes metal 7glitter logo\n💍 Example : *.7glitter ιnѕane*\n\n❄️Usage: *.1jewelry*\n✨Desc: it makes metal 1jewelry logo\n💍 Example : *.1jewelry ιnѕane*\n\n❄️Usage: *.2jewelry*\n✨Desc: it makes metal 2jewelry logo\n💍 Example : *.2jewelry ιnѕane*\n\n❄️Usage: *.3jewelry*\n✨Desc: it makes metal 3jewelry logo\n💍 Example : *.3jewelry ιnѕane*\n\n❄️Usage: *.4jewelry*\n✨Desc: it makes metal 4jewelry logo\n💍 Example : *.4jewelry ιnѕane*\n\n❄️Usage: *.5jewelry*\n✨Desc: it makes metal 5jewelry logo\n💍 Example : *.5jewelry ιnѕane*\n\n❄️Usage: *.6jewelry*\n✨Desc: it makes metal 6jewelry logo\n💍 Example : *.6jewelry ιnѕane*\n\n❄️Usage: *.7jewelry*\n✨Desc: it makes metal 7jewelry logo\n💍 Example : *.7jewelry ιnѕane*\n\n❄️Usage: *.8jewelry*\n✨Desc: it makes metal 8jewelry logo\n💍 Example : *.8jewelry ιnѕane*\n\n❄️Usage: *.honny*\n✨Desc: it makes metal honny logo\n💍 Example : *.honny ιnѕane*\n\n❄️Usage: *.rainbow*\n✨Desc: it makes metal rainbow logo\n💍 Example : *.rainbow ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·')
   }));
   
   Shazz.addCommand({pattern: 'logo3', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.3cake*\n✨Desc: it makes metal 3cake logo\n💍 Example : *.3cake ιnѕane*\n\n❄️Usage: *.captain*\n✨Desc: it makes metal captain logo\n💍 Example : *.captain ιnѕane*\n\n❄️Usage: *.bagel*\n✨Desc: it makes metal bagel logo\n💍 Example : *.bagel ιnѕane*\n\n❄️Usage: *.1gem*\n✨Desc: it makes metal 1gem logo\n💍 Example : *.1gem ιnѕane*\n\n❄️Usage: *.berry*\n✨Desc: it makes metal berry logo\n💍 Example : *.berry ιnѕane*\n\n❄️Usage: *.2blood*\n✨Desc: it makes metal 2blood logo\n💍 Example : *.2blood ιnѕane*\n\n❄️Usage: *.3blood*\n✨Desc: it makes metal 3blood logo\n💍 Example : *.3blood ιnѕane*\n\n❄️Usage: *.1glass*\n✨Desc: it makes metal 1glass logo\n💍 Example : *.1glass ιnѕane*\n\n❄️Usage: *.lava*\n✨Desc: it makes metal lava logo\n💍 Example : *.lava ιnѕane*\n\n❄️Usage: *.rock*\n✨Desc: it makes metal rock logo\n💍 Example : *.rock ιnѕane*\n\n❄️Usage: *.1decora*\n✨Desc: it makes metal 1decora logo\n💍 Example : *.1decora ιnѕane*\n\n❄️Usage: *.2decora*\n✨Desc: it makes metal 2decora logo\n💍 Example : *.2decora ιnѕane*\n\n❄️Usage: *.3decora*\n✨Desc: it makes metal 3decora logo\n💍 Example : *.3decora ιnѕane*\n\n❄️Usage: *.1foil*\n✨Desc: it makes metal 1foil logo\n💍 Example : *.1foil ιnѕane*\n\n❄️Usage: *.2foil*\n✨Desc: it makes metal 2foil logo\n💍 Example : *.2foil ιnѕane*\n\n❄️Usage: *.3foil*\n✨Desc: it makes metal 3foil logo\n💍 Example : *.3foil ιnѕane*\n\n❄️Usage: *.4foil*\n✨Desc: it makes metal 4foil logo\n💍 Example : *.4foil ιnѕane*\n\n❄️Usage: *.5foil*\n✨Desc: it makes metal 5foil logo\n💍 Example : *.5foil ιnѕane*\n\n❄️Usage: *.6foil*\n✨Desc: it makes metal 6foil logo\n💍 Example : *.6foil ιnѕane*\n\n❄️Usage: *.7foil*\n✨Desc: it makes metal 7foil logo\n💍 Example : *.7foil ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo4', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.steel*\n✨Desc: it makes metal steel logo\n💍 Example : *.steel ιnѕane*\n\n❄️Usage: *.1glossy*\n✨Desc: it makes metal 1glossy logo\n💍 Example : *.1glossy ιnѕane*\n\n❄️Usage: *.2glossy*\n✨Desc: it makes metal 2glossy logo\n💍 Example : *.2glossy ιnѕane*\n\n❄️Usage: *.denim*\n✨Desc: it makes metal denim logo\n💍 Example : *.denim ιnѕane*\n\n❄️Usage: *.joker*\n✨Desc: it makes metal joker logo\n💍 Example : *.joker ιnѕane*\n\n❄️Usage: *.wicker*\n✨Desc: it makes metal wicker logo\n💍 Example : *.wicker ιnѕane*\n\n❄️Usage: *.skeleton*\n✨Desc: it makes metal skeleton logo\n💍 Example : *.skeleton ιnѕane*\n\n❄️Usage: *.xmas3d*\n✨Desc: it makes metal xmas3d logo\n💍 Example : *.xmas3d ιnѕane*\n\n❄️Usage: *.helloween*\n✨Desc: it makes metal helloween logo\n💍 Example : *.helloween ιnѕane*\n\n❄️Usage: *.neon1s*\n✨Desc: it makes metal neon1s logo\n💍 Example : *.neon1s ιnѕane*\n\n❄️Usage: *.new1y*\n✨Desc: it makes metal new1y logo\n💍 Example : *.new1y ιnѕane*\n\n❄️Usage: *.1fabric*\n✨Desc: it makes metal 1fabric logo\n💍 Example : *.1fabric ιnѕane*\n\n❄️Usage: *.purpule*\n✨Desc: it makes metal purpule logo\n💍 Example : *.purpule ιnѕane*\n\n❄️Usage: *.holo3d*\n✨Desc: it makes metal holo3d logo\n💍 Example : *.holo3d ιnѕane*\n\n❄️Usage: *.minion3d*\n✨Desc: it makes metal minion3d logo\n💍 Example : *.minion3d ιnѕane*\n\n❄️Usage: *.neongalaxy*\n✨Desc: it makes metal neongalaxy logo\n💍 Example : *.neongalaxy ιnѕane*\n\n❄️Usage: *.darkgold*\n✨Desc: it makes metal darkgold logo\n💍 Example : *.darkgold ιnѕane*\n\n❄️Usage: *.1sandwriting*\n✨Desc: it makes metal 1sandwriting logo\n💍 Example : *.1sandwriting ιnѕane*\n\n❄️Usage: *.cloudsky*\n✨Desc: it makes metal cloudsky logo\n💍 Example : *.cloudsky ιnѕane*\n\n❄️Usage: *.3dluxury*\n✨Desc: it makes metal 3dluxury logo\n💍 Example : *.3dluxury ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));
   
   Shazz.addCommand({pattern: 'logo', fromMe: false, dontAddCommandList: true}, (async (message, match) => {
      await message.sendMessage('```👑*˩σɢσ мακɛя*👑```\n*𝙻𝙾𝙶𝙾 𝙼𝙰𝙺𝙸𝙽𝙶 𝚃𝙾𝙾𝙻 𝙷𝙴𝙻𝙿 𝚃𝙾 𝙼𝙰𝙺𝙴 𝙻𝙾𝙶𝙾*\n\n❄️Usage: *.sandsum*\n✨Desc: it makes metal sandsum logo\n💍 Example : *.sandsum ιnѕane*\n\n❄️Usage: *.1917*\n✨Desc: it makes metal 1917 logo\n💍 Example : *.1917 ιnѕane*\n\n❄️Usage: *.vlogo*\n✨Desc: it makes metal vlogo logo\n💍 Example : *.vlogo ιnѕane*\n\n❄️Usage: *.plogo*\n✨Desc: it makes metal plogo logo\n💍 Example : *.plogo ιnѕane*\n\n❄️Usage: *.colorlogo*\n✨Desc: it makes metal colorlogo logo\n💍 Example : *.colorlogo ιnѕane*\n\n\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n... *𝚁𝙴 𝙼𝙾𝙳𝙴𝙳 𝙱𝚈 𝚂𝙷𝙰𝙷𝙸𝙳-𝙳𝙴𝚅𝙸𝙻*n*𝚂𝙿𝙴𝙲𝙸𝙰𝙻 𝚃𝙷𝙰𝙽𝙺𝚂 𝚃𝙾 :𝙵𝙰𝚁𝙷𝙰𝙽 𝚂𝙸𝚁* ...\n· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·· ··÷¦÷·· ·\n')
   }));

}
